### ISSUE TITLE
Missing contribution guidelines and how-to for running the project locally

### ISSUE THREAD

**Issue by kbayliss** [torchbox/storybook-django#11]
The README includes a [broken link for contributing](https://github.com/torchbox/storybook-django/blob/main/README.md?plain=1#L369) referencing https://github.com/torchbox/storybook-django/blob/main/CONTRIBUTING.md

How do I set up the `storybook-django` project locally to explore?

**Comment by thibaudcolas** [comment]
👋 contribution guidelines were hiding in the `docs` folder, I’ve fixed the broken link now.
