### ISSUE TITLE
can i use this to build my own server side pattern library aimed at tailwindcss?

### ISSUE THREAD

**Issue by simkimsia** [torchbox/storybook-django#3]
Hi there, 

I am a bit confused tho I am familiar with Django.

Currently I use [django-tailwind](https://github.com/timonweb/django-tailwind) which requires me to create a separate `theme` app inside my Django project.

I like to build a UI component library so that 

1. the components can be reused within the same Django project
2. and then eventually I can make it reusable across all Django projects that also use django-tailwind

Given this in mind, do I still follow the instructions given here to first install [django-pattern-library](https://github.com/torchbox/django-pattern-library) followed by the npm installation of storybook-django and selecting HTML for the storybook template?

**Comment by thibaudcolas** [comment]
Hey @simkimsia, good question. I think you should follow the instructions on [django-pattern-library](https://github.com/torchbox/django-pattern-library) only, for now. storybook-django is built on top, the only thing it does is providing a more modern UI to view the pattern library components and a slightly nicer development experience.

It’s still very experimental though, and for what you said you were after it’d probably be simpler to avoid it for now.

**Comment by simkimsia** [comment]
I'll give it a try then 

Thank you
