### ISSUE TITLE
Would be good if a bit more information is provided for getting started

### ISSUE THREAD

**Issue by simkimsia** [torchbox/storybook-django#4]
![image](https://user-images.githubusercontent.com/245021/128379880-4a345d6b-bae1-41ac-8480-2b77e7e82e5f.png)

THink best to indicate that Yes to proceed and No to manually choose storybook project

**Comment by thibaudcolas** [comment]
I’ve just revamped the docs with a much clearer "getting started" section. Hope this helps! https://github.com/torchbox/storybook-django#getting-started
