### ISSUE TITLE
What does it mean to copy `demo/storybook` into your project?

### ISSUE THREAD

**Issue by simkimsia** [torchbox/storybook-django#5]
I have finished the installation for django-pattern-library.

![image](https://user-images.githubusercontent.com/245021/128382702-7338b8ef-c845-45dd-b30a-c172400ebab1.png)

i have finished with npx and npm install commands.

Then i see a copy `demo/storybook` into the project. Copy to where exactly?

And why do I need to copy given that i already npm install storybook-django?

![image](https://user-images.githubusercontent.com/245021/128380973-504e495a-f409-44a4-9234-b69d84fc1643.png)

**Comment by thibaudcolas** [comment]
The docs should now be much clearer and not mention the `demo` folder at all – there are code examples for everything relevant directly in the README: https://github.com/torchbox/storybook-django#getting-started
